# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/camilo/Documents/UFOP/19.1/POO/Trabalhos/inicial

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/camilo/Documents/UFOP/19.1/POO/Trabalhos/inicial

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/camilo/Documents/UFOP/19.1/POO/Trabalhos/inicial/CMakeFiles /home/camilo/Documents/UFOP/19.1/POO/Trabalhos/inicial/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/camilo/Documents/UFOP/19.1/POO/Trabalhos/inicial/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

Empresa/Empresa.o: Empresa/Empresa.cpp.o

.PHONY : Empresa/Empresa.o

# target to build an object file
Empresa/Empresa.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Empresa/Empresa.cpp.o
.PHONY : Empresa/Empresa.cpp.o

Empresa/Empresa.i: Empresa/Empresa.cpp.i

.PHONY : Empresa/Empresa.i

# target to preprocess a source file
Empresa/Empresa.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Empresa/Empresa.cpp.i
.PHONY : Empresa/Empresa.cpp.i

Empresa/Empresa.s: Empresa/Empresa.cpp.s

.PHONY : Empresa/Empresa.s

# target to generate assembly for a file
Empresa/Empresa.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Empresa/Empresa.cpp.s
.PHONY : Empresa/Empresa.cpp.s

Endereco/Endereco.o: Endereco/Endereco.cpp.o

.PHONY : Endereco/Endereco.o

# target to build an object file
Endereco/Endereco.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Endereco/Endereco.cpp.o
.PHONY : Endereco/Endereco.cpp.o

Endereco/Endereco.i: Endereco/Endereco.cpp.i

.PHONY : Endereco/Endereco.i

# target to preprocess a source file
Endereco/Endereco.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Endereco/Endereco.cpp.i
.PHONY : Endereco/Endereco.cpp.i

Endereco/Endereco.s: Endereco/Endereco.cpp.s

.PHONY : Endereco/Endereco.s

# target to generate assembly for a file
Endereco/Endereco.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Endereco/Endereco.cpp.s
.PHONY : Endereco/Endereco.cpp.s

Operations/Operations.o: Operations/Operations.cpp.o

.PHONY : Operations/Operations.o

# target to build an object file
Operations/Operations.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operations/Operations.cpp.o
.PHONY : Operations/Operations.cpp.o

Operations/Operations.i: Operations/Operations.cpp.i

.PHONY : Operations/Operations.i

# target to preprocess a source file
Operations/Operations.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operations/Operations.cpp.i
.PHONY : Operations/Operations.cpp.i

Operations/Operations.s: Operations/Operations.cpp.s

.PHONY : Operations/Operations.s

# target to generate assembly for a file
Operations/Operations.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operations/Operations.cpp.s
.PHONY : Operations/Operations.cpp.s

Pessoa/Desempregado/Desempregado.o: Pessoa/Desempregado/Desempregado.cpp.o

.PHONY : Pessoa/Desempregado/Desempregado.o

# target to build an object file
Pessoa/Desempregado/Desempregado.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Pessoa/Desempregado/Desempregado.cpp.o
.PHONY : Pessoa/Desempregado/Desempregado.cpp.o

Pessoa/Desempregado/Desempregado.i: Pessoa/Desempregado/Desempregado.cpp.i

.PHONY : Pessoa/Desempregado/Desempregado.i

# target to preprocess a source file
Pessoa/Desempregado/Desempregado.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Pessoa/Desempregado/Desempregado.cpp.i
.PHONY : Pessoa/Desempregado/Desempregado.cpp.i

Pessoa/Desempregado/Desempregado.s: Pessoa/Desempregado/Desempregado.cpp.s

.PHONY : Pessoa/Desempregado/Desempregado.s

# target to generate assembly for a file
Pessoa/Desempregado/Desempregado.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Pessoa/Desempregado/Desempregado.cpp.s
.PHONY : Pessoa/Desempregado/Desempregado.cpp.s

Pessoa/Pessoa.o: Pessoa/Pessoa.cpp.o

.PHONY : Pessoa/Pessoa.o

# target to build an object file
Pessoa/Pessoa.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Pessoa/Pessoa.cpp.o
.PHONY : Pessoa/Pessoa.cpp.o

Pessoa/Pessoa.i: Pessoa/Pessoa.cpp.i

.PHONY : Pessoa/Pessoa.i

# target to preprocess a source file
Pessoa/Pessoa.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Pessoa/Pessoa.cpp.i
.PHONY : Pessoa/Pessoa.cpp.i

Pessoa/Pessoa.s: Pessoa/Pessoa.cpp.s

.PHONY : Pessoa/Pessoa.s

# target to generate assembly for a file
Pessoa/Pessoa.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Pessoa/Pessoa.cpp.s
.PHONY : Pessoa/Pessoa.cpp.s

Populate/Populate.o: Populate/Populate.cpp.o

.PHONY : Populate/Populate.o

# target to build an object file
Populate/Populate.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Populate/Populate.cpp.o
.PHONY : Populate/Populate.cpp.o

Populate/Populate.i: Populate/Populate.cpp.i

.PHONY : Populate/Populate.i

# target to preprocess a source file
Populate/Populate.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Populate/Populate.cpp.i
.PHONY : Populate/Populate.cpp.i

Populate/Populate.s: Populate/Populate.cpp.s

.PHONY : Populate/Populate.s

# target to generate assembly for a file
Populate/Populate.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Populate/Populate.cpp.s
.PHONY : Populate/Populate.cpp.s

Util/Util.o: Util/Util.cpp.o

.PHONY : Util/Util.o

# target to build an object file
Util/Util.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Util/Util.cpp.o
.PHONY : Util/Util.cpp.o

Util/Util.i: Util/Util.cpp.i

.PHONY : Util/Util.i

# target to preprocess a source file
Util/Util.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Util/Util.cpp.i
.PHONY : Util/Util.cpp.i

Util/Util.s: Util/Util.cpp.s

.PHONY : Util/Util.s

# target to generate assembly for a file
Util/Util.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Util/Util.cpp.s
.PHONY : Util/Util.cpp.s

Vagas/Vagas.o: Vagas/Vagas.cpp.o

.PHONY : Vagas/Vagas.o

# target to build an object file
Vagas/Vagas.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Vagas/Vagas.cpp.o
.PHONY : Vagas/Vagas.cpp.o

Vagas/Vagas.i: Vagas/Vagas.cpp.i

.PHONY : Vagas/Vagas.i

# target to preprocess a source file
Vagas/Vagas.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Vagas/Vagas.cpp.i
.PHONY : Vagas/Vagas.cpp.i

Vagas/Vagas.s: Vagas/Vagas.cpp.s

.PHONY : Vagas/Vagas.s

# target to generate assembly for a file
Vagas/Vagas.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Vagas/Vagas.cpp.s
.PHONY : Vagas/Vagas.cpp.s

functions/functions.o: functions/functions.cpp.o

.PHONY : functions/functions.o

# target to build an object file
functions/functions.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/functions.cpp.o
.PHONY : functions/functions.cpp.o

functions/functions.i: functions/functions.cpp.i

.PHONY : functions/functions.i

# target to preprocess a source file
functions/functions.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/functions.cpp.i
.PHONY : functions/functions.cpp.i

functions/functions.s: functions/functions.cpp.s

.PHONY : functions/functions.s

# target to generate assembly for a file
functions/functions.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/functions/functions.cpp.s
.PHONY : functions/functions.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... Empresa/Empresa.o"
	@echo "... Empresa/Empresa.i"
	@echo "... Empresa/Empresa.s"
	@echo "... Endereco/Endereco.o"
	@echo "... Endereco/Endereco.i"
	@echo "... Endereco/Endereco.s"
	@echo "... Operations/Operations.o"
	@echo "... Operations/Operations.i"
	@echo "... Operations/Operations.s"
	@echo "... Pessoa/Desempregado/Desempregado.o"
	@echo "... Pessoa/Desempregado/Desempregado.i"
	@echo "... Pessoa/Desempregado/Desempregado.s"
	@echo "... Pessoa/Pessoa.o"
	@echo "... Pessoa/Pessoa.i"
	@echo "... Pessoa/Pessoa.s"
	@echo "... Populate/Populate.o"
	@echo "... Populate/Populate.i"
	@echo "... Populate/Populate.s"
	@echo "... Util/Util.o"
	@echo "... Util/Util.i"
	@echo "... Util/Util.s"
	@echo "... Vagas/Vagas.o"
	@echo "... Vagas/Vagas.i"
	@echo "... Vagas/Vagas.s"
	@echo "... functions/functions.o"
	@echo "... functions/functions.i"
	@echo "... functions/functions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

